apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: test-resiliency
scopes:
  - test-client

spec:
  policies:
    retries:
      retryForever:
        policy: constant
        duration: 5s
        maxRetries: -1 

    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 5s 
        trip: consecutiveFailures >= 5

  targets:
    apps:
      test-server:
        retry: retryForever
        circuitBreaker: simpleCB